version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - yarn install
  build:
    commands:
      - yarn run build
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: dist